import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative min-h-screen`}
      >
        {/* Background image */}
        <div
          aria-hidden
          className="fixed inset-0 -z-20 bg-[url('/green-smoothie-empty-notepad.jpg')] bg-cover bg-center bg-fixed"
        />

        {/* Soft overlay for readability */}
        <div
          aria-hidden
          className='fixed inset-0 -z-10 bg-white/70 dark:bg-black/50 backdrop-blur-[2px]'
        />

        {/* Page content */}
        <div className='relative z-10 min-h-screen'>{children}</div>
      </body>
    </html>
  );
}
